version: "2.1"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    logging:
      driver: none
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 5s
      timeout: 2s
      retries: 3

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elastic:9200
    depends_on:
      elastic:
        condition: service_healthy
    logging:
      driver: none

  jaeger:
    image: jaegertracing/all-in-one:1.30
    ports:
      - 16686:16686 #UI
      - 6831:6831   #COLLECTOR
      - 16685:16685   #Grpc api
    depends_on:
      elastic:
        condition: service_healthy
    environment:
      SPAN_STORAGE_TYPE: elasticsearch
      ES_SERVER_URLS: http://elastic:9200

  grafana:
    image: grafana/grafana:8.1.2
    ports:
      - "1337:3000"
    environment:
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831